name: Build and publish a Docker image

on: [push]

jobs:
  build:
    name: Build & push docker image
    runs-on: ubuntu-latest

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_PAT }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: loahit/perception-v1:1.0

    
 

